version: '3.8'

services:
  clear-bridge:
    build: .
    container_name: clear-bridge
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/usr/src/app
